In [1]:
import numpy as np 
import pandas as pd

In [6]:
array = np.random.randint(0,100,10)

In [7]:
array

array([71, 95,  0, 20, 18, 88, 14, 45, 89, 42])

In [10]:
array.reshape(2,5)

array([[71, 95,  0, 20, 18],
       [88, 14, 45, 89, 42]])

In [11]:
new_array = np.arange(0,100,20)

In [12]:
new_array

array([ 0, 20, 40, 60, 80])

In [13]:
a = np.arange(2*2*4).reshape((2,2,4))

In [14]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [23]:
a=np.arange(25).reshape(5,5)
b=np.random.randint(0,25,25)
b = b.reshape(5,5)
print(a )
print("\n")
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


[[17  0  9  5 24]
 [ 6  8  4  2  5]
 [17 24  9 24  3]
 [ 6 19 16 15 12]
 [23 17 16 14 15]]


In [24]:
c = np.multiply(a,b)
c

array([[  0,   0,  18,  15,  96],
       [ 30,  48,  28,  16,  45],
       [170, 264, 108, 312,  42],
       [ 90, 304, 272, 270, 228],
       [460, 357, 352, 322, 360]])

In [25]:
c = np.add(a,b)
c

array([[17,  1, 11,  8, 28],
       [11, 14, 11, 10, 14],
       [27, 35, 21, 37, 17],
       [21, 35, 33, 33, 31],
       [43, 38, 38, 37, 39]])

In [28]:
w = np.array([1,0,0,1,4])
b = 7
print(c)
print("\n")
print(w.T)

y = np.multiply(c,w.T) + b 
y 

[[17  1 11  8 28]
 [11 14 11 10 14]
 [27 35 21 37 17]
 [21 35 33 33 31]
 [43 38 38 37 39]]


[1 0 0 1 4]


array([[ 24,   7,   7,  15, 119],
       [ 18,   7,   7,  17,  63],
       [ 34,   7,   7,  44,  75],
       [ 28,   7,   7,  40, 131],
       [ 50,   7,   7,  44, 163]])

In [30]:
train = pd.read_csv("test.csv")

In [32]:
train.describe()

INT_SQFT  DIST_MAINROAD    N_BEDROOM   N_BATHROOM       N_ROOM  \
count  2925.000000    2925.000000  2925.000000  2925.000000  2925.000000   
mean   1393.779829      97.096068     1.652308     1.220513     3.723077   
std     447.345710      58.477193     0.787513     0.414663     0.989979   
min     500.000000       0.000000     1.000000     1.000000     2.000000   
25%    1006.000000      46.000000     1.000000     1.000000     3.000000   
50%    1442.000000      95.000000     1.000000     1.000000     4.000000   
75%    1744.000000     147.000000     2.000000     1.000000     4.000000   
max    2500.000000     200.000000     4.000000     2.000000     6.000000   

          QS_ROOMS  QS_BATHROOM   QS_BEDROOM   QS_OVERALL       REG_FEE  \
count  2925.000000  2925.000000  2925.000000  2906.000000  2.925000e+03   
mean      3.517504     3.476410     3.503282     3.505382  3.816600e+05   
std       0.885223     0.890613     0.895900     0.525879  1.390614e+05   
min       2.000000     2.000000     2.000000     2.050000  8.079200e+04   
25%       2.700000     2.700000     2.700000     3.130000  2.790940e+05   
50%       3.500000     3.500000     3.500000     3.500000  3.544790e+05   
75%       4.300000     4.200000     4.300000     3.890000  4.602210e+05   
max       5.000000     5.000000     5.000000     4.960000  1.029389e+06   

              COMMIS  
count    2925.000000  
mean   140409.045128  
std     76524.289615  
min      5200.000000  
25%     85368.000000  
50%    126352.000000  
75%    182531.000000  
max    514695.000000

In [33]:
train[['INT_SQFT','N_ROOM']]

INT_SQFT  N_ROOM
0          958       3
1         1807       5
2         1658       4
3         1592       4
4          857       3
5         1818       5
6         1584       4
7         1860       5
8         1701       4
9          868       3
10        1313       3
11        1785       5
12        1608       4
13         832       3
14        1818       5
15        1730       4
16        1122       3
17        1606       4
18        1976       5
19        1954       5
20        1030       3
21        1222       4
22         856       3
23        1957       5
24        1011       3
25        1725       4
26        1238       4
27        1691       4
28        2085       5
29        1021       3
...        ...     ...
2895      1599       4
2896      1886       5
2897      1769       4
2898       692       2
2899       716       2
2900      1254       4
2901      1270       4
2902      1651       4
2903      2200       5
2904      1486       4
2905      2114       5
2906      1666       4
2907      1896       5
2908       994       3
2909      1180       3
2910      1800       4
2911      1445       4
2912      1763       4
2913      1883       5
2914      1984       5
2915       518       2
2916      1598       4
2917       734       2
2918       862       3
2919       791       2
2920      1784       4
2921      1074       3
2922      1548       4
2923      1527       4
2924      1089       3

[2925 rows x 2 columns]

In [35]:
train.head(10)

PRT_ID        AREA  INT_SQFT   DATE_SALE  DIST_MAINROAD  N_BEDROOM  \
0  P05996    Chrompet       958  13-11-2009            185          1   
1  P09294  Anna Nagar      1807  29-01-2007            108          2   
2  P03807  Karapakkam      1658  07-01-2011             59          2   
3  P00539  Anna Nagar      1592  22-01-2014            102          1   
4  P01448    Chrompet       857  01-05-2012             62          1   
5  P06667    KK Nagar      1818  30-06-2009             12          3   
6  P09803   Velachery      1584  12-06-2005            186          2   
7  P05568  Anna Nagar      1860  02-02-2010             59          2   
8  P05102   Velachery      1701  01-05-2010             16          2   
9  P04556       Adyar       868  09-08-2010            182          1   

   N_BATHROOM  N_ROOM    SALE_COND PARK_FACIL   ...     BUILDTYPE  \
0           1       3     AbNormal         No   ...        Others   
1           1       5      AdjLand        Yes   ...        Others   
2           2       4      AdjLand         No   ...        Others   
3           1       4     AbNormal        Yes   ...        Others   
4           1       3       Family         No   ...         House   
5           2       5      Partial         No   ...    Commercial   
6           1       4  Normal Sale        Yes   ...    Commercial   
7           1       5  Normal Sale        Yes   ...    Commercial   
8           1       4       Family         No   ...    Commercial   
9           1       3  Normal Sale         No   ...         House   

  UTILITY_AVAIL     STREET MZZONE QS_ROOMS  QS_BATHROOM  QS_BEDROOM  \
0       NoSewr       Paved     RH      3.1          4.4         3.9   
1        NoSeWa  No Access     RM      2.6          4.1         2.1   
2        NoSeWa      Paved      I      2.5          2.3         3.2   
3        AllPub     Gravel     RL      4.1          4.8         2.5   
4           ELO     Gravel     RH      3.0          4.5         2.9   
5        NoSeWa      Paved     RH      2.6          2.6         2.0   
6        NoSeWa      Paved     RM      3.6          3.9         2.4   
7           ELO     Gravel     RL      3.5          4.0         2.0   
8           ELO     Gravel     RM      3.0          2.0         3.5   
9        NoSeWa      Paved      A      3.3          3.9         4.1   

   QS_OVERALL  REG_FEE  COMMIS  
0       3.860   203260   93813  
1       2.775   370410  222246  
2       2.720   387972  113159  
3       3.635   408134   84442  
4       3.570   181212   34849  
5       2.360   472463  305712  
6       3.380   533096  103657  
7       3.025   849269  304866  
8       2.700   447233  238524  
9       3.820   186898    5664  

[10 rows x 21 columns]

In [37]:
train.drop('AREA',axis=1,inplace=True)

In [38]:
train.head()

PRT_ID  INT_SQFT   DATE_SALE  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  N_ROOM  \
0  P05996       958  13-11-2009            185          1           1       3   
1  P09294      1807  29-01-2007            108          2           1       5   
2  P03807      1658  07-01-2011             59          2           2       4   
3  P00539      1592  22-01-2014            102          1           1       4   
4  P01448       857  01-05-2012             62          1           1       3   

  SALE_COND PARK_FACIL  DATE_BUILD BUILDTYPE UTILITY_AVAIL     STREET MZZONE  \
0  AbNormal         No  20-11-1982    Others       NoSewr       Paved     RH   
1   AdjLand        Yes  02-02-1990    Others        NoSeWa  No Access     RM   
2   AdjLand         No  11-01-1995    Others        NoSeWa      Paved      I   
3  AbNormal        Yes  27-01-1995    Others        AllPub     Gravel     RL   
4    Family         No  10-05-1978     House           ELO     Gravel     RH   

   QS_ROOMS  QS_BATHROOM  QS_BEDROOM  QS_OVERALL  REG_FEE  COMMIS  
0       3.1          4.4         3.9       3.860   203260   93813  
1       2.6          4.1         2.1       2.775   370410  222246  
2       2.5          2.3         3.2       2.720   387972  113159  
3       4.1          4.8         2.5       3.635   408134   84442  
4       3.0          4.5         2.9       3.570   181212   34849

In [42]:
train.drop(0,axis=0,inplace=True)

In [43]:
train.head()

PRT_ID  INT_SQFT   DATE_SALE  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  N_ROOM  \
1  P09294      1807  29-01-2007            108          2           1       5   
2  P03807      1658  07-01-2011             59          2           2       4   
3  P00539      1592  22-01-2014            102          1           1       4   
4  P01448       857  01-05-2012             62          1           1       3   
5  P06667      1818  30-06-2009             12          3           2       5   

  SALE_COND PARK_FACIL  DATE_BUILD   BUILDTYPE UTILITY_AVAIL     STREET  \
1   AdjLand        Yes  02-02-1990      Others        NoSeWa  No Access   
2   AdjLand         No  11-01-1995      Others        NoSeWa      Paved   
3  AbNormal        Yes  27-01-1995      Others        AllPub     Gravel   
4    Family         No  10-05-1978       House           ELO     Gravel   
5   Partial         No  02-07-2000  Commercial        NoSeWa      Paved   

  MZZONE  QS_ROOMS  QS_BATHROOM  QS_BEDROOM  QS_OVERALL  REG_FEE  COMMIS  
1     RM       2.6          4.1         2.1       2.775   370410  222246  
2      I       2.5          2.3         3.2       2.720   387972  113159  
3     RL       4.1          4.8         2.5       3.635   408134   84442  
4     RH       3.0          4.5         2.9       3.570   181212   34849  
5     RH       2.6          2.6         2.0       2.360   472463  305712

In [47]:
train.iloc[10:15,0:5]

PRT_ID  INT_SQFT   DATE_SALE  DIST_MAINROAD  N_BEDROOM
11  P02221      1785  13-11-2011             37          3
12  P03299      1608  18-04-2011             19          2
13  P08959       832  04-06-2007             67          1
14  P09377      1818  30-12-2006            105          3
15  P09924      1730  26-09-2004             71          2

In [48]:
train["new"] = train["INT_SQFT"] + train["N_BEDROOM"]

In [49]:
train["new"]

1       1809
2       1660
3       1593
4        858
5       1821
6       1586
7       1862
8       1703
9        869
10      1314
11      1788
12      1610
13       833
14      1821
15      1732
16      1123
17      1608
18      1978
19      1957
20      1031
21      1224
22       857
23      1960
24      1012
25      1727
26      1240
27      1692
28      2088
29      1022
30      1515
        ... 
2895    1601
2896    1889
2897    1771
2898     693
2899     717
2900    1256
2901    1272
2902    1653
2903    2203
2904    1488
2905    2117
2906    1668
2907    1898
2908     995
2909    1181
2910    1802
2911    1447
2912    1765
2913    1885
2914    1986
2915     519
2916    1600
2917     735
2918     863
2919     792
2920    1785
2921    1075
2922    1549
2923    1529
2924    1090
Name: new, Length: 2924, dtype: int64